### ISSUE TITLE
Travis IOS build problem

### ISSUE THREAD

**Issue by Saifsliti** [mobileappdevhm19/campus-connected-team-6#56]
Nachdem ich den IOS Ordner (travis.yml) in Flutter konfiguriert habe, schafft es dennoch Travis die App nicht zu bilden. 
Das ist die Fehlermeldung von Travis : 'The job exceeded the maximum log length, and has been terminated.'
Bitte in diese Branch (travis_fix_ios_build) schauen.

**Comment by RedTo** [comment]
Mehr als googlen und mutmaßen kann ich hier leider auch nicht.

Folgende Möglichkeiten sehe ich:
- Ausgabe reduzieren, wenn möglich keine unwichtigen Statusmeldungen der einzelnen Kommandos ausgeben
- Andere osx version testen?
- Nach alternativen Konfigurationen suchen

Bevor ich euch damit aber aufhaltet, finde ich es in erster Linie wichtiger, dass eure App vernünftige Features implementiert hat. Um die Travis-Builds könnt ihr euch auch anschließend noch kümmern.

Ich werde mal schauen, ob ich hier vielleicht etwas passendes finden kann, das euch weiterhilft...
